version: '3'
services:
    day4-rails-docker-for-run:
        container_name: day4-rails-docker-for-run
        build:
            context: .
            dockerfile: Dockerfile_for_dev
        command: rails s -b 0.0.0.0 -e development
        working_dir: /rails_app_dir/my_rails_app
        volumes:
            - ./my_rails_app:/rails_app_dir/my_rails_app
        ports:
            - '3000:3000'
        networks:
            - db

networks:
    db:
        driver: bridge


