FROM ruby:2.5.0-slim
RUN apt-get update && apt-get install -qq -y build-essential nodejs --fix-missing --no-install-recommends
RUN apt-get install -qq -y sqlite3 libsqlite3-dev --fix-missing --no-install-recommends
RUN gem install rails

COPY my_rails_app/Gemfile Gemfile
RUN bundle install
