version: '3'
services:
    day1-flask-vol:
        container_name: day3-flask-vol-mysql
        build: .
        environment:
            FLASK_APP: app.py 
            FLASK_DEBUG: 1 #make you edit app.py file and view the change without restart server.
        command: flask run --host=0.0.0.0 --port=5000 #start with port 5000 within its container
        links:
            - mysql-dev
        volumes:
            - ./web:/app/web
              #- ./web:/app/web:ro #readonly for the folder
        ports:
            - '8000:5000' #http://localhost:8000 mapping to your local port 8000 
        command: flask run --host=0.0.0.0 --port=5000 #start with port 5000 within its container 
        networks:
            - db

    mysql-dev:
        image: mysql:5.5
        container_name: mysql5.5-dev
        environment:
            MYSQL_ROOT_PASSWORD: abcdefg
        ports:
            - '3306:3306'
        networks:
            - db
networks:
    db:
        driver: bridge
